services:
  php:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ../app:/usr/share/nginx/html
    depends_on:
      - nginx
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx
    restart: always
    volumes:
      - ../app:/usr/share/nginx/html
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app-network

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ../database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
