services:
  php:
    build:
      dockerfile: ./Dockerfile
    container_name: PHP-NODEJS
    volumes:
      - ../app:/usr/share/nginx/html
    ports:
      - "9003:9003"  # Puerto para Xdebug
    depends_on:
      - nginx
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx
    restart: always
    container_name: NGINX
    volumes:
      - ../app:/usr/share/nginx/html
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app-network

  mysql:
    image: mysql
    restart: always
    container_name: MYSQL
    ports:
      - 3306:3306
    volumes:
      - ../database/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    networks:
      - app-network

  postgresql:
    image: postgres:17.2
    restart: always
    container_name: POSTGRES
    ports:
      - "5432:5432"
    volumes:
      - ../database/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network


  redis:
    image: redis:7.2-alpine
    restart: always
    container_name: REDIS
    ports:
      - "6379:6379"
    volumes:
      - ../database/redis:/data
    environment:
      REDIS_PASSWORD: redis
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
